##################################
#### SINA_VARASINA Animations ####
##################################

animations {
    enabled = true
    
    bezier = easeOutExpo, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 1.5, easeOutExpo, popin 90%
    animation = windowsOut, 1, 1.5, easeOutExpo, popin 90%
    
    animation = border, 0, 1, easeOutExpo
    animation = borderangle, 0, 1, easeOutExpo

    animation = fade, 1, 1.5, easeOutExpo
    
    animation = workspaces, 1, 1.5, easeOutExpo, slidefade 15%
    
    animation = layers, 1, 1.5, easeOutExpo, fade
    animation = specialWorkspace, 1, 1.5, easeOutExpo, slidevert
}
