##################################
#### SINA_VARASINA Decoration ####
##################################

decoration {
    rounding = 0 

  shadow {
        enabled = true
        range = 15
        render_power = 2 
        color = rgba(11111baa) 
  }

  blur {
        enabled = yes
        size = 5
        passes = 2
        noise = 0.03
        contrast = 1.2
        new_optimizations = true
  }
}
