##################################
##### SINA_VARASINA GENERAL ######
##################################

general {
    gaps_in = 1
    gaps_out = 1

    border_size = 1

    col.active_border = rgb(cba6f7) rgb(313244) 45deg 

    col.inactive_border = rgb(181825) 

    resize_on_border = true 
    allow_tearing = true
    layout = dwindle 
}
