##################################
### SINA_VARASINA MASTER-LAYOUT ##
##################################

master {
    new_status = slave
    allow_small_split = true
    mfact = 0.55
    new_on_top = true
}
