##################################
###### SINA_VARASINA RENDER ######
##################################

render {
    direct_scanout = 2
    ctm_animation = 2
    cm_fs_passthrough = 2
    cm_enabled = 1
    send_content_type = true 
}
