##################################
##### SINA_VARASINA HYPRPAPER ####
##################################

preload = /home/sina/Pictures/Wallpapers/Yuki-Gentoo-wallpaper-r2.png
wallpaper {
    monitor = DP-1
    path = /home/sina/dotfiles/wallpapers/Yuki-Gentoo-wallpaper-r2.png
    fit_mode = cover
}
splash = off
