# ============================================================
#  hypridle.conf — Idle Daemon
# ============================================================

general {
  ignore_dbus_inhibit = false
}

listener {
  timeout = 580
  on-timeout = hyprctl notify 3 30000 "rgb(ffaa00)" "Idle Warning: Display will turn off in 30 seconds"
  
  on-resume = hyprctl notify 1 5000 "rgb(00ff00)" "Activity detected: Welcome back."
}

listener {
  timeout = 610
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
