##################################
##### SINA_VARASINA HYPRPAPER ####
##################################

preload = /home/sina/Pictures/Wallpapers/Yuki-Gentoo-wallpaper-r2.png
wallpaper {
    monitor = DP-1
    path = /home/sina/Pictures/Yuki-Gentoo-wallpaper-r9.png
    fit_mode = cover
}
ipc = on
splash = off
