##################################
##### SINA_VARASINA HYPRPAPER ####
##################################

preload = /home/sina/Pictures/Wallpapers/monogatari1.jpg
wallpaper =  DP-1,/home/sina/Pictures/Wallpapers/monogatari1.jpg
ipc = on
splash = off
