# ============================================================
#  hyprtoolkit.conf — Toolkit Settings
# ============================================================

background = 0xFF11111B
base = 0xFF1E1E2E
text = 0xFFCDD6F4
alternate_base = 0xFF313244
bright_text = 0xFFF5E0DC

accent = 0xFFCBA6F7
accent_secondary = 0xFF54487A

font_family = MesloLGS Nerd Font
font_family_monospace = BlexMono Nerd Font
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0

icon_theme = Arc
