##################################
### SINA_VARASINA MonitorConf ####
##################################

# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
# }
 monitorv2 {
     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
     mode = 1920x1080@180
     position = auto
     scale = 1 
     bitdepth = 10
 }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = auto
# }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = wide
# }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = hdr
# }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = hdredid
# }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = hdr
#     sdrbrightness = 1.3
#     sdrsaturation = 1.05
# }
# monitorv2 {
#     output = desc:Xiaomi Corporation Mi Monitor 5790020017103
#     mode = 1920x1080@180
#     position = auto
#     scale = 1 
#     bitdepth = 10
#     cm = hdr
#     sdrbrightness = 1.1
# }

