##################################
### SINA_VARASINA StartUP-APPS ###
##################################

# Waybar 
exec-once = waybar &

# Hyprpolkit
exec-once = systemctl --user start hyprpolkitagent

# xdg-desktop-portal-hyprland.sh
# exec-once = XDPH

# IME
exec-once = fcitx5 &

# Wallpaper
# exec-once = hyprpaper &
exec-once = swaybg -i /home/sina/dotfiles/wallpapers/Yuki-Gentoo-wallpaper-r2.png -m fill &

# Notifications Daemon 
exec-once = dunst &

# Thunar Daemon
exec-once = thunar --daemon

# Foot Server
exec-once = foot --server

# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Mount Disk Automatically at Start-up
exec-once = $automount 

# Hypridle turn off display 
exec-once = hypridle

# Mixer
# exec-once = easyeffects --gapplication-service
