##################################
### SINA_VARASINA WorkspaceRule ##
##################################

# smart gaps
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = border_size 0, match:float 0, match:workspace f[1]s[false]
windowrule = rounding 0, match:float 0, match:workspace f[1]s[false]

# workspace layout
workspace = 5, layout:master
workspace = 6, layout:monocle
workspace = 7, layout:scrolling
