#================================
# Main
#================================
[main]
font=BlexMono Nerd Font Mono:size=8, Noto Color Emoji:size=8, Noto Sans CJK JP:size=8, MesloLGS Nerd Font Mono:size=8
#pad=8x8

#================================
# Colors
#================================
[colors]
alpha=0.95
background=24273a
foreground=cad3f5

## Normal
regular0=494d64
regular1=ed8796
regular2=a6da95
regular3=eed49f
regular4=8aadf4
regular5=f5bde6
regular6=8bd5ca
regular7=b8c0e0

## Bright
bright0=5b6078
bright1=ed8796
bright2=a6da95
bright3=eed49f
bright4=8aadf4
bright5=f5bde6
bright6=8bd5ca
bright7=a5adce

#===============================
# Cursor & URL
#===============================
[cursor]
style=block

#===============================
# Scrollback & Key Bindings
#===============================
[scrollback]
lines=10000

[key-bindings]
font-increase=Control+plus
font-decrease=Control+minus
font-reset=Control+0
